import { subDays, subHours } from "date-fns";

import type {
  DashboardData,
  IntegrationStatus,
  Lead,
  OutreachThread,
  ProfileSettings,
} from "@/lib/types";
import { buildDashboardStats } from "@/lib/outreach";

export const defaultSettings: ProfileSettings = {
  id: "profile",
  fullName: "Saarth Ranka",
  firstName: "Saarth",
  schoolName: "Monta Vista High School",
  districtName: "FUHSD / Cupertino area",
  city: "Cupertino",
  state: "California",
  targetSeason: "Summer 2027 internship, remote or Bay Area",
  remotePreference: "Remote preferred, in-person okay around Cupertino",
  internshipPreference: "Founding teams, AI tools, startups, research-adjacent internships",
  availabilityNotes:
    "Needs a realistic estimate of weekly commitment. Parent-supported. Open to remote and local summer work.",
  tone: "Plain, direct, short sentences. States what he did and stops.",
  accomplishments: [
    "Robotics intern at DeepAware AI in San Francisco, June to August 2026: motors, assembly and control software for their OpenArm robot arms, and ran the arms table solo at their Builders Conference in front of about 200 people",
    "Engineering intern at Frizzle (YC S25), May to August 2026: built the cold email infrastructure they ran at about 1,000 sends a day, plus a grant scraper and a writing tool",
    "Ships with AI tools solo: two command line tools for his school, a Schoology dashboard, and a ride sharing app he runs a six person team on",
    "Built and grew Ascenta, a Vercel + Firebase gaming and proxy site, to 20 paying customers at school",
    "Trades futures on a funded account and builds systematic strategies against the IBKR API",
  ],
  skills: [
    "Robotics: motor control, assembly, control software",
    "Email infrastructure and deliverability at volume",
    "Shipping full products with AI-assisted development",
    "Reading and debugging code he did not write",
    "Running a small engineering team",
  ],
  closingNotes:
    "Two startup internships done at 14. Looking for the next one, not for a favour.",
  dailySendTarget: 18,
  followUpWindowDays: 9,
  parentSupport: "Parent-supported and available during the summer.",
};

export const demoIntegration: IntegrationStatus = {
  connected: false,
  emailAddress: "ranka.saarth@gmail.com",
  watchExpiresAt: null,
  lastSyncedAt: null,
  mode: "demo",
};

export const demoLeads: Lead[] = [
  {
    id: "lead-openai-tools",
    companyName: "OpenAI Tooling Lab",
    website: "https://example-ai-tools.com",
    domain: "example-ai-tools.com",
    companyType: "AI tools startup",
    location: "Remote / SF",
    contactEmail: "careers@example-ai-tools.com",
    contactName: null,
    contactType: "careers",
    source: "Public careers page",
    confidence: 0.92,
    status: "queued",
    followUpDate: subDays(new Date(), -5).toISOString(),
    notes: "Strong fit for product-minded generalist outreach.",
    lastThreadId: "thread-queued-1",
  },
  {
    id: "lead-founder-micro",
    companyName: "Signal Forge",
    website: "https://signalforge.ai",
    domain: "signalforge.ai",
    companyType: "Founder-led AI startup",
    location: "SF",
    contactEmail: "founders@signalforge.ai",
    contactName: "Founding team",
    contactType: "founder",
    source: "Public about page",
    confidence: 0.88,
    status: "sent",
    followUpDate: subDays(new Date(), -2).toISOString(),
    notes: "Mention bot-building and willingness to work unpaid.",
    lastThreadId: "thread-sent-1",
  },
  {
    id: "lead-invalid-demo",
    companyName: "Nimbus Research",
    website: "https://nimbusresearch.ai",
    domain: "nimbusresearch.ai",
    companyType: "Applied AI research startup",
    location: "Remote",
    contactEmail: "jobs@nimbusresearch.ai",
    contactName: null,
    contactType: "general",
    source: "Contact page",
    confidence: 0.37,
    status: "skipped",
    followUpDate: null,
    notes: "Opted out after the contact inbox looked too risky for a cold email.",
    lastThreadId: null,
  },
  {
    id: "lead-yes-demo",
    companyName: "Axiom Vision",
    website: "https://axiomvision.ai",
    domain: "axiomvision.ai",
    companyType: "Computer vision startup",
    location: "Remote / NYC",
    contactEmail: "team@axiomvision.ai",
    contactName: null,
    contactType: "general",
    source: "Public team inbox",
    confidence: 0.83,
    status: "sent",
    followUpDate: subDays(new Date(), -1).toISOString(),
    notes: "Already contacted from the workspace and kept in the sent history.",
    lastThreadId: "thread-yes-1",
  },
];

export const demoThreads: OutreachThread[] = [
  {
    id: "thread-queued-1",
    companyId: "lead-openai-tools",
    companyName: "OpenAI Tooling Lab",
    gmailThreadId: null,
    subject: "Summer internship interest from a Cupertino student builder",
    latestSnippet: "Draft is ready. Waiting for approval before sending.",
    gmailThreadUrl: null,
    bucket: "needs_reply",
    needsAttention: false,
    draftStatus: "ready",
    lastMessageAt: subHours(new Date(), 3).toISOString(),
    sentAt: null,
    draftBody:
      "Hey there,\n\nI'm Saarth Ranka, a Cupertino student who likes building fast with AI tools...",
    lastReplySummary: "No reply yet.",
    outcomeLabel: "Ready to send",
  },
  {
    id: "thread-sent-1",
    companyId: "lead-founder-micro",
    companyName: "Signal Forge",
    gmailThreadId: "18f-demo-thread",
    subject: "Summer internship interest from Saarth Ranka",
    latestSnippet: "Sent 2 days ago. Follow-up due soon.",
    gmailThreadUrl: "https://mail.google.com/mail/u/0/#inbox/FMfcgzQdemo1",
    bucket: "no",
    needsAttention: false,
    draftStatus: "sent",
    lastMessageAt: subDays(new Date(), 2).toISOString(),
    sentAt: subDays(new Date(), 2).toISOString(),
    draftBody:
      "Hey there,\n\nI’m a high-school student in Cupertino who ships quickly and loves AI products...",
    lastReplySummary: "Cold email sent from the workspace.",
    outcomeLabel: "Sent",
  },
  {
    id: "thread-yes-1",
    companyId: "lead-yes-demo",
    companyName: "Axiom Vision",
    gmailThreadId: "18f-demo-thread-2",
    subject: "Availability and summer internship question",
    latestSnippet: "Sent 4 days ago. Waiting to hear back from the team.",
    gmailThreadUrl: "https://mail.google.com/mail/u/0/#inbox/FMfcgzQdemo2",
    bucket: "no",
    needsAttention: false,
    draftStatus: "sent",
    lastMessageAt: subHours(new Date(), 8).toISOString(),
    sentAt: subDays(new Date(), 4).toISOString(),
    draftBody:
      "Hey there,\n\nI’m reaching out because I’d love to help an ambitious AI team this summer...",
    lastReplySummary: "Initial outreach is in flight.",
    outcomeLabel: "Sent",
  },
];

export function buildDemoDashboardData(): DashboardData {
  return {
    settings: defaultSettings,
    integration: demoIntegration,
    stats: buildDashboardStats(demoLeads, demoThreads, defaultSettings.dailySendTarget),
    leads: demoLeads,
    threads: demoThreads,
  };
}
