import { subDays, subHours } from "date-fns";

import type {
  DashboardData,
  IntegrationStatus,
  Lead,
  OutreachThread,
  ProfileSettings,
} from "@/lib/types";
import { buildDashboardStats } from "@/lib/outreach";

export const defaultSettings: ProfileSettings = {
  id: "profile",
  fullName: "Saarth Ranka",
  firstName: "Saarth",
  schoolName: "Monta Vista High School",
  districtName: "CUSDK8 / Cupertino area",
  city: "Cupertino",
  state: "California",
  targetSeason: "Summer internship, unpaid okay, remote preferred",
  remotePreference: "Remote preferred, in-person okay around Cupertino",
  internshipPreference: "Founding teams, AI tools, startups, research-adjacent internships",
  availabilityNotes:
    "Needs a realistic estimate of weekly commitment. Parent-supported. Open to remote and local summer work.",
  tone: "Calm, curious, slightly bold, ambitious, respectful",
  accomplishments: [
    "Built and grew Ascenta, a Vercel + Firebase-backed gaming and proxy site, to 20 paying customers at school",
    "Built autonomous trading strategies that execute live via the IBKR API, plus additional strategies with Streamlit dashboards",
    "Has traded options and futures for roughly 4 years and is developing systematic strategies using LLMs and Pine Script",
    "Played tabla for 9 years, teaches at a local temple, and placed second in the Chaitradhun national competition",
  ],
  skills: [
    "LLM-assisted product building",
    "Fast shipping with Vercel and Firebase",
    "Scrappy debugging and iteration",
    "Trading automation exploration",
    "Discipline from long-term music training",
  ],
  closingNotes:
    "Open to any role where strong curiosity, fast execution, and willingness to learn are useful.",
  dailySendTarget: 18,
  followUpWindowDays: 9,
  parentSupport: "Parent-supported and available during the summer.",
};

export const demoIntegration: IntegrationStatus = {
  connected: false,
  emailAddress: "ranka.saarth@gmail.com",
  watchExpiresAt: null,
  lastSyncedAt: null,
  mode: "demo",
};

export const demoLeads: Lead[] = [
  {
    id: "lead-openai-tools",
    companyName: "OpenAI Tooling Lab",
    website: "https://example-ai-tools.com",
    domain: "example-ai-tools.com",
    companyType: "AI tools startup",
    location: "Remote / SF",
    contactEmail: "careers@example-ai-tools.com",
    contactName: null,
    contactType: "careers",
    source: "Public careers page",
    confidence: 0.92,
    status: "queued",
    followUpDate: subDays(new Date(), -5).toISOString(),
    notes: "Strong fit for product-minded generalist outreach.",
    lastThreadId: "thread-queued-1",
  },
  {
    id: "lead-founder-micro",
    companyName: "Signal Forge",
    website: "https://signalforge.ai",
    domain: "signalforge.ai",
    companyType: "Founder-led AI startup",
    location: "SF",
    contactEmail: "founders@signalforge.ai",
    contactName: "Founding team",
    contactType: "founder",
    source: "Public about page",
    confidence: 0.88,
    status: "sent",
    followUpDate: subDays(new Date(), -2).toISOString(),
    notes: "Mention bot-building and willingness to work unpaid.",
    lastThreadId: "thread-sent-1",
  },
  {
    id: "lead-invalid-demo",
    companyName: "Nimbus Research",
    website: "https://nimbusresearch.ai",
    domain: "nimbusresearch.ai",
    companyType: "Applied AI research startup",
    location: "Remote",
    contactEmail: "jobs@nimbusresearch.ai",
    contactName: null,
    contactType: "general",
    source: "Contact page",
    confidence: 0.37,
    status: "skipped",
    followUpDate: null,
    notes: "Opted out after the contact inbox looked too risky for a cold email.",
    lastThreadId: null,
  },
  {
    id: "lead-yes-demo",
    companyName: "Axiom Vision",
    website: "https://axiomvision.ai",
    domain: "axiomvision.ai",
    companyType: "Computer vision startup",
    location: "Remote / NYC",
    contactEmail: "team@axiomvision.ai",
    contactName: null,
    contactType: "general",
    source: "Public team inbox",
    confidence: 0.83,
    status: "sent",
    followUpDate: subDays(new Date(), -1).toISOString(),
    notes: "Already contacted from the workspace and kept in the sent history.",
    lastThreadId: "thread-yes-1",
  },
];

export const demoThreads: OutreachThread[] = [
  {
    id: "thread-queued-1",
    companyId: "lead-openai-tools",
    companyName: "OpenAI Tooling Lab",
    gmailThreadId: null,
    subject: "Summer internship interest from a Cupertino student builder",
    latestSnippet: "Draft is ready. Waiting for approval before sending.",
    gmailThreadUrl: null,
    bucket: "needs_reply",
    needsAttention: false,
    draftStatus: "ready",
    lastMessageAt: subHours(new Date(), 3).toISOString(),
    sentAt: null,
    draftBody:
      "Hey there,\n\nI'm Saarth Ranka, a Cupertino student who likes building fast with AI tools...",
    lastReplySummary: "No reply yet.",
    outcomeLabel: "Ready to send",
  },
  {
    id: "thread-sent-1",
    companyId: "lead-founder-micro",
    companyName: "Signal Forge",
    gmailThreadId: "18f-demo-thread",
    subject: "Summer internship interest from Saarth Ranka",
    latestSnippet: "Sent 2 days ago. Follow-up due soon.",
    gmailThreadUrl: "https://mail.google.com/mail/u/0/#inbox/FMfcgzQdemo1",
    bucket: "no",
    needsAttention: false,
    draftStatus: "sent",
    lastMessageAt: subDays(new Date(), 2).toISOString(),
    sentAt: subDays(new Date(), 2).toISOString(),
    draftBody:
      "Hey there,\n\nI’m a high-school student in Cupertino who ships quickly and loves AI products...",
    lastReplySummary: "Cold email sent from the workspace.",
    outcomeLabel: "Sent",
  },
  {
    id: "thread-yes-1",
    companyId: "lead-yes-demo",
    companyName: "Axiom Vision",
    gmailThreadId: "18f-demo-thread-2",
    subject: "Availability and summer internship question",
    latestSnippet: "Sent 4 days ago. Waiting to hear back from the team.",
    gmailThreadUrl: "https://mail.google.com/mail/u/0/#inbox/FMfcgzQdemo2",
    bucket: "no",
    needsAttention: false,
    draftStatus: "sent",
    lastMessageAt: subHours(new Date(), 8).toISOString(),
    sentAt: subDays(new Date(), 4).toISOString(),
    draftBody:
      "Hey there,\n\nI’m reaching out because I’d love to help an ambitious AI team this summer...",
    lastReplySummary: "Initial outreach is in flight.",
    outcomeLabel: "Sent",
  },
];

export function buildDemoDashboardData(): DashboardData {
  return {
    settings: defaultSettings,
    integration: demoIntegration,
    stats: buildDashboardStats(demoLeads, demoThreads),
    leads: demoLeads,
    threads: demoThreads,
  };
}
